/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120523-g31bad42d54-20250806"
#endif /* AVUTIL_FFVERSION_H */
